<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\Representation;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Representation;
use Axtiva\FlexibleGraphql\Resolver\FederationRepresentationResolverInterface;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Representation resolver for federated graphql type Profile
 */
final class ProfileRepresentation implements FederationRepresentationResolverInterface
{
    public function getTypeName(): string
    {
        return 'Profile';
    }

    public function __invoke(Representation $representation, $context, ResolveInfo $info)
    {
        throw new NotImplementedResolver('Not implemented field resolver ' . __CLASS__);
    }
}