<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\Representation;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Representation;
use Axtiva\FlexibleGraphql\Resolver\FederationRepresentationResolverInterface;
use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use UserService\Application\GraphQL\Mapper\UserMapper;
use UserService\Application\GraphQL\Model\UserType;
use UserService\Domain\UseCase\UserUseCase;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Representation resolver for federated graphql type User
 */
final class UserRepresentation implements FederationRepresentationResolverInterface
{
    public function __construct(
         private UserUseCase $useCase,
    )
    {
    }

    public function getTypeName(): string
    {
        return 'User';
    }

    public function __invoke(Representation $representation, $context, ResolveInfo $info): ?UserType
    {
        return UserMapper::map(
            $this->useCase->findById($representation->getFields()['id'])
        );
    }
}