<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\Representation;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Representation;
use Axtiva\FlexibleGraphql\Resolver\FederationRepresentationResolverInterface;
use UserService\Application\GraphQL\Mapper\UserFeatureFlagMapper;
use UserService\Application\GraphQL\Model\UserFeatureFlagType;
use UserService\Domain\UseCase\UserFeatureFlagUseCase;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * Representation resolver for federated graphql type UserFeatureFlag
 */
final readonly class UserFeatureFlagRepresentation implements FederationRepresentationResolverInterface
{
    public function __construct(
        private UserFeatureFlagUseCase $useCase,
    )
    {
    }

    public function getTypeName(): string
    {
        return 'UserFeatureFlag';
    }

    public function __invoke(Representation $representation, $context, ResolveInfo $info): ?UserFeatureFlagType
    {
        return UserFeatureFlagMapper::map(
            $this->useCase->findById($representation->getFields()['id'])
        );
    }
}