###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

services:
    apollo:
      build:
        context: .
        dockerfile: docker/node/Dockerfile
      container_name: apollo
      hostname: apollo
      working_dir: /app
      ports:
        - "4000:4000"
      networks:
        default:
          aliases:
            - apollo

    graphql-nginx:
      image: nginx:alpine
      container_name: user-service-nginx
      hostname: user-service-nginx
      working_dir: /var/www
      volumes:
        - ./php:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8090:80"

    user-service:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      container_name: user-service
      hostname: user-service
      working_dir: /var/www/
      volumes:
        - ./php:/var/www
        - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/99-overrides.ini
        - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      networks:
        default:
          aliases:
            - user-service-php

    book-service:
      build:
        context: .
        dockerfile: ./docker/golang/Dockerfile
      container_name: book-service
      hostname: book-service
      working_dir: /app
      networks:
        default:
          aliases:
            - book-service