###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

services:
    graphql-apollo:
      build:
        context: .
        dockerfile: docker/node/Dockerfile
      container_name: graphql-apollo
      hostname: graphql-apollo
      working_dir: /app
      volumes:
        - ./apollo:/app
      ports:
        - "4000:4000"
      networks:
        default:
          aliases:
            - graphql-apollo

    graphql-nginx:
      image: nginx:alpine
      container_name: plains-nginx
      hostname: graphql-nginx
      working_dir: /var/www
      volumes:
        - ./php:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8090:80"
      networks:
        default:
          aliases:
            - graphql-nginx

    graphql-php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      container_name: graphql-php
      hostname: graphql-php
      working_dir: /var/www/
      volumes:
        - ./php:/var/www
        - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/99-overrides.ini
        - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      networks:
        default:
          aliases:
            - graphql-php

    graphql-golang:
      build:
        context: .
        dockerfile: ./docker/golang/Dockerfile
      container_name: graphql-golang
      hostname: graphql-golang
      working_dir: /app
      networks:
        default:
          aliases:
            - graphql-golang