###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

services:
    apollo:
      build:
        context: .
        dockerfile: docker/node/Dockerfile
      container_name: apollo
      hostname: apollo
      working_dir: /app
      ports:
        - "4000:4000"
      networks:
        default:
          aliases:
            - apollo

    user-service:
      image: nginx:alpine
      container_name: user-service
      hostname: user-service
      working_dir: /var/www
      volumes:
        - ./user-service:/var/www
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8090:80"
      networks:
        default:
          aliases:
            - user-service

    book-service:
      build:
        context: .
        dockerfile: ./docker/golang/Dockerfile
      container_name: book-service
      hostname: book-service
      working_dir: /app
      networks:
        default:
          aliases:
            - book-service