<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\Resolver\Profile;

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use UserService\Application\GraphQL\Mapper\ProfileMapper;
use UserService\Application\GraphQL\Model\ProfileType;
use UserService\Application\GraphQL\Model\UserType;
use UserService\Domain\UseCase\ProfileUseCase;
use UserService\Domain\UseCase\UserUseCase;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Profile.user
 */
final readonly class UserResolver implements ResolverInterface
{
    public function __construct(
        private UserUseCase $useCase
    )
    {
    }

    /**
     * @param ProfileType $rootValue
     * @param $args
     * @param $context
     * @param ResolveInfo $info
     * @return UserType
     */
    public function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        return ProfileMapper::map(
            $this->useCase->findById($rootValue->get())
        );
    }
}