parameters:
  container.dumper.inline_factories: true

services:
  _defaults:
    autowire: true
    autoconfigure: true

  GraphqlApp\:
    resource: '../src/'
    exclude:
      - '../src/Application/Kernel.php'
  Psr\Container\ContainerInterface: '@service_container'