package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"graphql-golang/internal/application/graphql/generated"
	"graphql-golang/internal/application/graphql/model"
)

// FindBookByID is the resolver for the findBookByID field.
func (r *entityResolver) FindBookByID(ctx context.Context, id string) (*model.Book, error) {
	books, err := r.bookUseCase.FindByID(id)
	return mapBookToType(books), err
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return &model.User{
		ID: id,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
