package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"graphql-golang/internal/application/graphql/generated"
	"graphql-golang/internal/application/graphql/model"
)

// Summery is the resolver for the summery field.
func (r *bookResolver) Summery(ctx context.Context, obj *model.Book) (string, error) {
	return fmt.Sprintf("Sumery of %s", obj.Author.Email), nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	books := []*model.Book{
		{
			ID:    "1",
			Title: "Book 1",
			Author: model.User{
				ID:    "1",
				Email: "b1@test.com",
			},
		},
		{
			ID:    "2",
			Title: "Book 2",
			Author: model.User{
				ID:    "2",
				Email: "b2@test.com",
			},
		},
		{
			ID:    "3",
			Title: "Book 3",
			Author: model.User{
				ID:    "2",
				Email: "b2@test.com",
			},
		},
	}

	return books, nil
}

// Books is the resolver for the books field.
func (r *userResolver) Books(ctx context.Context, obj *model.User) ([]*model.Book, error) {
	books := []*model.Book{
		{
			ID:     "1",
			Title:  "Book 1",
			Author: *obj,
		},
		{
			ID:     "2",
			Title:  "Book 2",
			Author: *obj,
		},
		{
			ID:     "3",
			Title:  "Book 3",
			Author: *obj,
		},
	}

	return books, nil
}

// Book returns generated.BookResolver implementation.
func (r *Resolver) Book() generated.BookResolver { return &bookResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type bookResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
