<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\UnionResolveType;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\UnionResolveTypeInterface;
use UserService\Application\GraphQL\Model\UserType;
use UserService\Application\GraphQL\Model\ProfileType;
use UserService\Application\GraphQL\Model\UserFeatureFlagType;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * and will be regenerated. Do not edit it manually
 */
final class _EntityTypeResolver implements UnionResolveTypeInterface
{
    public function __invoke($model, $context, ResolveInfo $info)
    {
        if (isset($model)) {
            switch (get_class($model)) {
                case UserType::class:
                    return $info->schema->getType('User');
                case ProfileType::class:
                    return $info->schema->getType('Profile');
                case UserFeatureFlagType::class:
                    return $info->schema->getType('UserFeatureFlag');
            }
        }
        return null;
    }
}