<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\Resolver\User;

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use UserService\Application\GraphQL\Model\UserType;
use UserService\Application\GraphQL\Model\ProfileType;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for User.profile
 */
final class ProfileResolver implements ResolverInterface
{
    /**
     * @param UserType $rootValue
     * @param $args
     * @param $context
     * @param ResolveInfo $info
     * @return ProfileType[]
     */
    public function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        throw new NotImplementedResolver('Not implemented field resolver ' . __CLASS__);
    }
}