<?php

declare (strict_types=1);
namespace UserService\Application\GraphQL\Resolver\User;

use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;
use UserService\Application\GraphQL\Mapper\ProfileMapper;
use UserService\Application\GraphQL\Model\UserType;
use UserService\Application\GraphQL\Model\ProfileType;
use UserService\Domain\UseCase\ProfileUseCase;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for User.profile
 */
final readonly class ProfileResolver implements ResolverInterface
{
    public function __construct(
        private ProfileUseCase $useCase
    )
    {
    }

    /**
     * @param UserType $rootValue
     * @param $args
     * @param $context
     * @param ResolveInfo $info
     * @return ProfileType
     */
    public function __invoke($rootValue, $args, $context, ResolveInfo $info): ProfileType
    {
        return ProfileMapper::map(
            $this->useCase->findByUserId($rootValue->id)
        );
    }
}