<?php

declare (strict_types=1);
namespace GraphqlApp\Application\GraphQL\Resolver\Query;

use Axtiva\FlexibleGraphql\Generator\Exception\NotImplementedResolver;
use GraphQL\Type\Definition\ResolveInfo;
use Axtiva\FlexibleGraphql\Resolver\ResolverInterface;

/**
 * This code is @generated by axtiva/flexible-graphql-php
 * This is resolver for Query.myName
 */
final class MyNameResolver implements ResolverInterface
{
    /**
     * @param $rootValue
     * @param $args
     * @param $context
     * @param ResolveInfo $info
     * @return string
     */
    public function __invoke($rootValue, $args, $context, ResolveInfo $info)
    {
        return 'My name is John Doe!!!';
    }
}